server:
  port: 2001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/macysusecasedb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: consumer-service

management:
  server:
    port: 9090
  endpoints: 
     web:
       base-path: "/macys-usecase-actuator"
       exposure:
         include: "*"
  endpoint:
     health:
       show-details: always

spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  